### ISSUE TITLE
depends on vulnarable json-schema version. Please bump "request"

### ISSUE THREAD

**Issue by Mexx77** [kanthoney/odata-client#20]
Hey,

please bump the dependency **request** to not have the transient dependency on vulnerable json-schema < 0.4.0.

Thank you!

json-schema  <0.4.0
Severity: moderate
json-schema is vulnerable to Prototype Pollution - https://github.com/advisories/GHSA-896r-f27r-55mw
node_modules/json-schema
  jsprim  0.3.0 - 2.0.1
  Depends on vulnerable versions of json-schema
  node_modules/jsprim
    http-signature  1.0.0 - 1.3.5
    Depends on vulnerable versions of jsprim
    node_modules/http-signature
      request  >=2.66.0
      Depends on vulnerable versions of http-signature
      node_modules/request
        odata-client  *
        Depends on vulnerable versions of request
        node_modules/odata-client

**Comment by kanthoney** [comment]
I've bumped request to version 2.88.2, which is the latest available. That hasn't fixed the problem though - `npm audit` still shows the same vulnerabilities. It says that dropping to version 2.65.0 will clear those, but if I do that the result is lots more vulnerabilities, some of them critical.

I guess at some point I should switch to another package since request is deprecated, but that would break everything for people expecting request.

**Comment by Mexx77** [comment]
hey @kanthoney, thanks for your effort. :100:  
Why would people expect request? Its an internal dependency of odata-client, right? I, as consumer, only expect the interface being stable, odata-client is offering. Whats used under the hood, I don't (really) mind.

**Comment by kanthoney** [comment]
The problem is all the libraries do things slightly differently. For example, request will return a raw response, [`got`](https://npmjs.com/package/got) will return a response, but will throw an error if the status code isn't either 2xx or 3xx, and [`axios`](https://npmjs.com/package/axios) will return a simplified response that's completely different to the one that request gives.

Anyway, I've got a version that uses got instead (although it'll use request if that's installed), which you can try out by uninstalling `odata-client` and running

```
npm install https://github.com/kanthoney/odata-client/tree/request-deprecate
```

Once I've verified it works properly I'll push it to the main branch.

**Comment by Mexx77** [comment]
Thanks, I will try it out over the weekend and give you some feedback next week.

**Comment by Mexx77** [comment]
Its deployed since Friday and I observe nominal behavior :)

**Comment by kanthoney** [comment]
OK, I've published that version then. Thanks for the help.
